# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MatrixRain < Formula
  desc "Authentic Matrix digital rain terminal simulator written in Go"
  homepage "https://smford.github.io/matrix-rain"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smford/matrix-rain/releases/download/v1.1.0/matrix-rain_1.1.0_darwin_amd64.tar.gz"
      sha256 "7ea9582ddad8079552cc240edf157fe7756df53578b039f50dc02892a45f2495"

      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smford/matrix-rain/releases/download/v1.1.0/matrix-rain_1.1.0_darwin_arm64.tar.gz"
      sha256 "d25368be0efc062263d2deefb13bf6ceddb1baee9b100658728736da474994b1"

      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.1.0/matrix-rain_1.1.0_linux_amd64.tar.gz"
      sha256 "d1396a6d07c64ea2a589093114b6b8ec080b5a1254bdd0c6c752839c02327b10"
      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.1.0/matrix-rain_1.1.0_linux_arm64.tar.gz"
      sha256 "7d7592ff7d20ad87a830ca2a5ea419ce1b807198cd49f35927f5963a96a08f83"
      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
  end

  test do
    system "#{bin}/matrix-rain", "-version"
  end
end
