# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MatrixRain < Formula
  desc "Authentic Matrix digital rain terminal simulator written in Go"
  homepage "https://smford.github.io/matrix-rain"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_darwin_amd64.tar.gz"
      sha256 "04085571748945bf8579b8a517604ef76e30f4522a81e94f9dda1ea01b137496"

      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_darwin_arm64.tar.gz"
      sha256 "87330649452cc1300d9dd9d84d03d920cc6c58d0b98e8b5e5ee97dc3cca7f421"

      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_linux_amd64.tar.gz"
      sha256 "53ce820660039c492599d45176cf225a2953fa64b0f7c70b1a5b21ecdb30fe03"
      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.0/matrix-rain_1.0.0_linux_arm64.tar.gz"
      sha256 "7b34f03a32fccaf2100d5f105e086cefa2000f85c098af4f8eb6f08a091ef312"
      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
  end

  test do
    system "#{bin}/matrix-rain", "-version"
  end
end
