# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MatrixRain < Formula
  desc "Authentic Matrix digital rain terminal simulator written in Go"
  homepage "https://smford.github.io/matrix-rain"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.1/matrix-rain_1.0.1_darwin_amd64.tar.gz"
      sha256 "84a6ee61cb3b9396572c8cde5caf51189ce8c33f36506ad9c8ce6d534dbc6c0e"

      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.1/matrix-rain_1.0.1_darwin_arm64.tar.gz"
      sha256 "c17cb8bdfb5ce2ce530667abe125c3aa01513739ea2b75d34d3fb681deac4fe4"

      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.1/matrix-rain_1.0.1_linux_amd64.tar.gz"
      sha256 "44b7ff01a71375c4f3a12654ca2ffc55fb9ae0a9c96e0f1de6bb30d033912501"
      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-rain/releases/download/v1.0.1/matrix-rain_1.0.1_linux_arm64.tar.gz"
      sha256 "2dc0c2e18e100df50dea0d0234eb7edd312baf22d88536b5cbaa13be7cb0e288"
      define_method(:install) do
        bin.install "matrix-rain"
      end
    end
  end

  test do
    system "#{bin}/matrix-rain", "-version"
  end
end
