# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcat < Formula
  desc "Authentic Matrix digital rain terminal simulator and text viewer written in Go"
  homepage "https://smford.github.io/matrix-cat"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smford/matrix-cat/releases/download/v1.1.1/mcat_1.1.1_darwin_amd64.tar.gz"
      sha256 "099d241d4226cef1c443963dd5c1fc33dd8f010127b1e4ff7345d1635b56012a"

      define_method(:install) do
        bin.install "mcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smford/matrix-cat/releases/download/v1.1.1/mcat_1.1.1_darwin_arm64.tar.gz"
      sha256 "e4b25d88cf14369769c0f4127f888e775f0ac6f19c6d687cdd45ee66464dc839"

      define_method(:install) do
        bin.install "mcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-cat/releases/download/v1.1.1/mcat_1.1.1_linux_amd64.tar.gz"
      sha256 "01225ad76e8fd8d71dcd95c425f0108e0f209b2077f4252028a499e99909a5ba"
      define_method(:install) do
        bin.install "mcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-cat/releases/download/v1.1.1/mcat_1.1.1_linux_arm64.tar.gz"
      sha256 "fe00174f8f9b6c5aefe35bcaa826c3044fc0bfe5f6f78db44cdd125ff087a212"
      define_method(:install) do
        bin.install "mcat"
      end
    end
  end

  test do
    system "#{bin}/mcat", "-version"
  end
end
