# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mcat < Formula
  desc "Authentic Matrix digital rain terminal simulator and text viewer written in Go"
  homepage "https://smford.github.io/matrix-cat"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/smford/matrix-cat/releases/download/v1.2.0/mcat_1.2.0_darwin_amd64.tar.gz"
      sha256 "072e075d9a16afd3e83c7614cf262794fbcf0b12ab5fabd54ac442154f0fb49b"

      define_method(:install) do
        bin.install "mcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/smford/matrix-cat/releases/download/v1.2.0/mcat_1.2.0_darwin_arm64.tar.gz"
      sha256 "eef5c0a6c89e6132e93108323275530980837b32dc743cac15ee6d1e5ffcd51b"

      define_method(:install) do
        bin.install "mcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-cat/releases/download/v1.2.0/mcat_1.2.0_linux_amd64.tar.gz"
      sha256 "ceb0abe3f2e7da4167f888f820d7190a0293ca214398fa48187b350043af8956"
      define_method(:install) do
        bin.install "mcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/smford/matrix-cat/releases/download/v1.2.0/mcat_1.2.0_linux_arm64.tar.gz"
      sha256 "85632bb926b03988e06d92a14b0e8d26ab9442ba49b5c505c56c3a3e52a020d6"
      define_method(:install) do
        bin.install "mcat"
      end
    end
  end

  test do
    system "#{bin}/mcat", "-version"
  end
end
